background {
    monitor =
    path = ~/walls/windows-error.jpg
}

input-field {
    monitor =
    size = 400, 50
    outline_thickness = 3
    dots_size = 0.33 
    dots_spacing = 0.15 
    fade_on_empty = false
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 100
    font_family = JetBrains Mono Nerd Font
    position = 0, 300
    halign = center
    valign = center
}
